#!/usr/bin/env bash

[ ! -d .test ] && mkdir -p .test
go test -mutexprofile=.test/mutexprofile.out -cpuprofile=.test/cpuprofile.out -memprofile=.test/memprofile.out ./...
go test -cover -race -coverprofile=.test/coverage.out ./...
go test -trace=.test/trace.out ./...

[ ! -z "$COVERALLS_TOKEN" ] && goveralls -service circle-ci -repotoken=${COVERALLS_TOKEN} -coverprofile=.test/coverage.out
